### ISSUE TITLE
cannot import name 'SampleOutput' from 'transformers.generation.utils'

### ISSUE THREAD

**Issue by dijkstra-mose** [LowinLi/transformers-stream-generator#13]
Transformers stream generator does not match the latest version of Transformers?

transformers: 4.37.0
transformers-stream-generator：0.0.4

```
$ python
Python 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] on linux
>>> import transformers_stream_generator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/anaconda3/envs/train/lib/python3.10/site-packages/transformers_stream_generator/__init__.py", line 1, in <module>
    from .main import init_stream_support
  File "/home/work/anaconda3/envs/train/lib/python3.10/site-packages/transformers_stream_generator/main.py", line 16, in <module>
    from transformers.generation.utils import GenerateOutput, SampleOutput, logger
ImportError: cannot import name 'SampleOutput' from 'transformers.generation.utils' (/home/work/anaconda3/envs/train/lib/python3.10/site-packages/transformers/generation/utils.py)
```

**Comment by NiuBlibing** [comment]
Maybe https://github.com/huggingface/transformers/issues/28649
